# Laboratorio 3: 

## Integrantes:

- Escriba
- Garcia
- Mayhua

---

In [1]:
# Importamos las librerias a utilizar

import pandas as pd
import numpy as np

## Parte A

In [2]:
#Leemos los datos

data = pd.read_csv("banca.csv", sep = ';')
data

age          job  marital            education  default housing loan  \
0       56    housemaid  married             basic.4y       no      no   no   
1       57     services  married          high.school  unknown      no   no   
2       37     services  married          high.school       no     yes   no   
3       40       admin.  married             basic.6y       no      no   no   
4       56     services  married          high.school       no      no  yes   
...    ...          ...      ...                  ...      ...     ...  ...   
41183   73      retired  married  professional.course       no     yes   no   
41184   46  blue-collar  married  professional.course       no      no   no   
41185   56      retired  married    university.degree       no     yes   no   
41186   44   technician  married  professional.course       no      no   no   
41187   74      retired  married  professional.course       no     yes   no   

         contact month day_of_week  ...  campaign  pdays  previous  \
0      telephone   may         mon  ...         1    999         0   
1      telephone   may         mon  ...         1    999         0   
2      telephone   may         mon  ...         1    999         0   
3      telephone   may         mon  ...         1    999         0   
4      telephone   may         mon  ...         1    999         0   
...          ...   ...         ...  ...       ...    ...       ...   
41183   cellular   nov         fri  ...         1    999         0   
41184   cellular   nov         fri  ...         1    999         0   
41185   cellular   nov         fri  ...         2    999         0   
41186   cellular   nov         fri  ...         1    999         0   
41187   cellular   nov         fri  ...         3    999         1   

          poutcome emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  \
0      nonexistent          1.1          93.994          -36.4      4.857   
1      nonexistent          1.1          93.994          -36.4      4.857   
2      nonexistent          1.1          93.994          -36.4      4.857   
3      nonexistent          1.1          93.994          -36.4      4.857   
4      nonexistent          1.1          93.994          -36.4      4.857   
...            ...          ...             ...            ...        ...   
41183  nonexistent         -1.1          94.767          -50.8      1.028   
41184  nonexistent         -1.1          94.767          -50.8      1.028   
41185  nonexistent         -1.1          94.767          -50.8      1.028   
41186  nonexistent         -1.1          94.767          -50.8      1.028   
41187      failure         -1.1          94.767          -50.8      1.028   

       nr.employed    y  
0           5191.0   no  
1           5191.0   no  
2           5191.0   no  
3           5191.0   no  
4           5191.0   no  
...            ...  ...  
41183       4963.6  yes  
41184       4963.6   no  
41185       4963.6   no  
41186       4963.6  yes  
41187       4963.6   no  

[41188 rows x 21 columns]

In [3]:
# Seleccionamos la partes numericas

v_numericas = data.select_dtypes(["float64","int64"])



In [4]:
#convirtiendo el dataframe a matriz

X = v_numericas.to_numpy()
X


array([[ 5.6000e+01,  2.6100e+02,  1.0000e+00, ..., -3.6400e+01,
         4.8570e+00,  5.1910e+03],
       [ 5.7000e+01,  1.4900e+02,  1.0000e+00, ..., -3.6400e+01,
         4.8570e+00,  5.1910e+03],
       [ 3.7000e+01,  2.2600e+02,  1.0000e+00, ..., -3.6400e+01,
         4.8570e+00,  5.1910e+03],
       ...,
       [ 5.6000e+01,  1.8900e+02,  2.0000e+00, ..., -5.0800e+01,
         1.0280e+00,  4.9636e+03],
       [ 4.4000e+01,  4.4200e+02,  1.0000e+00, ..., -5.0800e+01,
         1.0280e+00,  4.9636e+03],
       [ 7.4000e+01,  2.3900e+02,  3.0000e+00, ..., -5.0800e+01,
         1.0280e+00,  4.9636e+03]])

In [5]:
X.shape

(41188, 10)

## PARTE B

In [6]:
# Vector de medias para cada variables

Medias = np.mean(X,axis = 0)
Medias

array([ 4.00240604e+01,  2.58285010e+02,  2.56759250e+00,  9.62475454e+02,
        1.72962999e-01,  8.18855006e-02,  9.35756644e+01, -4.05026003e+01,
        3.62129081e+00,  5.16703591e+03])

In [7]:
# Resta de la matriz de datos y el vector de medias

Resta= X - Medias
Resta

array([[  15.97593959,    2.7149898 ,   -1.5675925 , ...,    4.10260027,
           1.23570919,   23.96408906],
       [  16.97593959, -109.2850102 ,   -1.5675925 , ...,    4.10260027,
           1.23570919,   23.96408906],
       [  -3.02406041,  -32.2850102 ,   -1.5675925 , ...,    4.10260027,
           1.23570919,   23.96408906],
       ...,
       [  15.97593959,  -69.2850102 ,   -0.5675925 , ...,  -10.29739973,
          -2.59329081, -203.43591094],
       [   3.97593959,  183.7149898 ,   -1.5675925 , ...,  -10.29739973,
          -2.59329081, -203.43591094],
       [  33.97593959,  -19.2850102 ,    0.4324075 , ...,  -10.29739973,
          -2.59329081, -203.43591094]])

In [8]:
# Matriz de covariana de las variables
Covarianza = np.cov(X, rowvar=False)
Covarianza

array([[ 1.08602451e+02, -2.33914694e+00,  1.32602905e-01,
        -6.69453996e+01,  1.25660856e-01, -6.06862678e-03,
         5.16790762e-03,  6.23980083e+00,  1.94622473e-01,
        -1.33461599e+01],
       [-2.33914694e+00,  6.72257289e+04, -5.14948884e+01,
        -2.30568302e+03,  2.64851986e+00, -1.13918021e+01,
         7.97271590e-01, -9.80741194e+00, -1.47938307e+01,
        -8.37439866e+02],
       [ 1.32602905e-01, -5.14948884e+01,  7.67297503e+00,
         2.72249214e+01, -1.08493675e-01,  6.56017208e-01,
         2.04971433e-01, -1.76060671e-01,  6.49236419e-01,
         2.88388223e+01],
       [-6.69453996e+01, -2.30568302e+03,  2.72249214e+01,
         3.49356873e+04, -5.43464475e+01,  7.95748230e+01,
         8.53513249e+00, -7.90166771e+01,  9.62508736e+01,
         5.03187748e+03],
       [ 1.25660856e-01,  2.64851986e+00, -1.08493675e-01,
        -5.43464475e+01,  2.44927079e-01, -3.26917530e-01,
        -5.81903503e-02, -1.16669718e-01, -3.90128214e-01,
        -1.

In [9]:
# Inversa de la matriz  de covarianza de las variables

Inversa = np.linalg.inv(Covarianza)
Inversa

array([[ 9.38173198e-03,  3.34861347e-07, -4.19763601e-04,
         1.36121285e-06, -3.83502917e-03,  5.91771204e-03,
        -3.34866075e-03, -2.57771661e-03, -6.23700615e-03,
         6.72917534e-05],
       [ 3.34861347e-07,  1.50158934e-05,  9.62870679e-05,
         9.83273819e-07,  2.49779398e-04,  6.70782611e-06,
        -1.19291115e-04,  2.30610883e-05, -1.93072125e-04,
         6.38651062e-06],
       [-4.19763601e-04,  9.62870679e-05,  1.35335551e-01,
         1.09911594e-05,  1.42838208e-02, -6.63710866e-02,
        -8.70631753e-02, -4.79336291e-03,  1.41186158e-01,
        -2.19436697e-03],
       [ 1.36121285e-06,  9.83273819e-07,  1.09911594e-05,
         4.62235336e-05,  9.18864731e-03,  2.31031936e-04,
         1.76824294e-03,  2.62003352e-04, -4.10047095e-04,
        -1.72357243e-05],
       [-3.83502917e-03,  2.49779398e-04,  1.42838208e-02,
         9.18864731e-03,  7.33548730e+00, -3.74523111e-01,
         4.38774276e-01,  6.87595024e-02, -7.94986119e-02,
         2.

## Parte C

In [10]:
# Multiplicando la 
n = X.shape[0]
valores = []
for i in range (n):
    valor = np.dot(np.dot(Resta[i],Inversa),Resta[i].T)
    valores.append(valor)
valores

[np.float64(4.255314704970985),
 np.float64(4.7641252469305),
 np.float64(2.3812791810885914),
 np.float64(2.4173933966218515),
 np.float64(4.2736463830906555),
 np.float64(2.406397685900043),
 np.float64(5.4339007870763725),
 np.float64(2.232331409715643),
 np.float64(5.128205236172272),
 np.float64(5.3748172234073595),
 np.float64(2.8894415695215034),
 np.float64(4.675301631202809),
 np.float64(3.846720821359419),
 np.float64(4.5491594393899275),
 np.float64(2.7797253443471943),
 np.float64(3.875203845344764),
 np.float64(2.569353924105843),
 np.float64(2.8369444148903966),
 np.float64(3.0224006676328528),
 np.float64(2.319006450708545),
 np.float64(4.17431647305917),
 np.float64(3.986002346934688),
 np.float64(4.061075721539904),
 np.float64(2.3102437970680096),
 np.float64(2.4982924222191416),
 np.float64(2.9896124459661655),
 np.float64(5.647562336099434),
 np.float64(2.2538328169790907),
 np.float64(3.4292781822095812),
 np.float64(4.1098758520538565),
 np.float64(2.4969755204799

In [11]:
from scipy.spatial.distance import mahalanobis 

f = X.shape[0]
valoresmaha = []
for i in range (f):
    valor = mahalanobis(X[i],Medias,Inversa)**2
    valoresmaha.append(valor)
valoresmaha

[np.float64(4.255314704970983),
 np.float64(4.764125246930498),
 np.float64(2.3812791810885914),
 np.float64(2.4173933966218515),
 np.float64(4.273646383090655),
 np.float64(2.406397685900042),
 np.float64(5.433900787076372),
 np.float64(2.2323314097156435),
 np.float64(5.128205236172271),
 np.float64(5.374817223407358),
 np.float64(2.889441569521502),
 np.float64(4.6753016312028075),
 np.float64(3.846720821359418),
 np.float64(4.549159439389928),
 np.float64(2.779725344347193),
 np.float64(3.875203845344763),
 np.float64(2.569353924105843),
 np.float64(2.8369444148903953),
 np.float64(3.022400667632853),
 np.float64(2.3190064507085446),
 np.float64(4.174316473059169),
 np.float64(3.986002346934688),
 np.float64(4.061075721539902),
 np.float64(2.3102437970680088),
 np.float64(2.4982924222191407),
 np.float64(2.9896124459661646),
 np.float64(5.6475623360994325),
 np.float64(2.2538328169790898),
 np.float64(3.4292781822095812),
 np.float64(4.1098758520538565),
 np.float64(2.4969755204799

In [12]:
data['Mahalanobis'] = valores
data ['Indices'] = data.index
data

age          job  marital            education  default housing loan  \
0       56    housemaid  married             basic.4y       no      no   no   
1       57     services  married          high.school  unknown      no   no   
2       37     services  married          high.school       no     yes   no   
3       40       admin.  married             basic.6y       no      no   no   
4       56     services  married          high.school       no      no  yes   
...    ...          ...      ...                  ...      ...     ...  ...   
41183   73      retired  married  professional.course       no     yes   no   
41184   46  blue-collar  married  professional.course       no      no   no   
41185   56      retired  married    university.degree       no     yes   no   
41186   44   technician  married  professional.course       no      no   no   
41187   74      retired  married  professional.course       no     yes   no   

         contact month day_of_week  ...  previous     poutcome  emp.var.rate  \
0      telephone   may         mon  ...         0  nonexistent           1.1   
1      telephone   may         mon  ...         0  nonexistent           1.1   
2      telephone   may         mon  ...         0  nonexistent           1.1   
3      telephone   may         mon  ...         0  nonexistent           1.1   
4      telephone   may         mon  ...         0  nonexistent           1.1   
...          ...   ...         ...  ...       ...          ...           ...   
41183   cellular   nov         fri  ...         0  nonexistent          -1.1   
41184   cellular   nov         fri  ...         0  nonexistent          -1.1   
41185   cellular   nov         fri  ...         0  nonexistent          -1.1   
41186   cellular   nov         fri  ...         0  nonexistent          -1.1   
41187   cellular   nov         fri  ...         1      failure          -1.1   

       cons.price.idx cons.conf.idx  euribor3m  nr.employed    y  Mahalanobis  \
0              93.994         -36.4      4.857       5191.0   no     4.255315   
1              93.994         -36.4      4.857       5191.0   no     4.764125   
2              93.994         -36.4      4.857       5191.0   no     2.381279   
3              93.994         -36.4      4.857       5191.0   no     2.417393   
4              93.994         -36.4      4.857       5191.0   no     4.273646   
...               ...           ...        ...          ...  ...          ...   
41183          94.767         -50.8      1.028       4963.6  yes    63.591979   
41184          94.767         -50.8      1.028       4963.6   no    52.691288   
41185          94.767         -50.8      1.028       4963.6   no    55.386806   
41186          94.767         -50.8      1.028       4963.6  yes    52.541504   
41187          94.767         -50.8      1.028       4963.6   no    61.169682   

       Indices  
0            0  
1            1  
2            2  
3            3  
4            4  
...        ...  
41183    41183  
41184    41184  
41185    41185  
41186    41186  
41187    41187  

[41188 rows x 23 columns]

In [13]:
data = data[data["Mahalanobis"] > 100 ]
data = data.drop(['Mahalanobis', 'Indices'], axis =1)
data

age            job   marital            education  default  housing  \
2313    39  self-employed   married             basic.4y  unknown      yes   
4107    32         admin.   married    university.degree  unknown  unknown   
4114    52   entrepreneur   married    university.degree       no       no   
4139    52     management   married             basic.4y  unknown       no   
4168    29     technician   married  professional.course       no      yes   
...    ...            ...       ...                  ...      ...      ...   
41144   35         admin.    single  professional.course       no      yes   
41153   67      housemaid  divorced  professional.course       no      yes   
41164   54         admin.   married  professional.course       no       no   
41170   40     management  divorced    university.degree       no      yes   
41174   62        retired   married    university.degree       no      yes   

          loan    contact month day_of_week  ...  previous     poutcome  \
2313        no  telephone   may         tue  ...         0  nonexistent   
4107   unknown  telephone   may         mon  ...         0  nonexistent   
4114        no  telephone   may         mon  ...         0  nonexistent   
4139        no  telephone   may         mon  ...         0  nonexistent   
4168        no  telephone   may         mon  ...         0  nonexistent   
...        ...        ...   ...         ...  ...       ...          ...   
41144       no   cellular   nov         fri  ...         4      failure   
41153       no   cellular   nov         mon  ...         5      success   
41164       no   cellular   nov         tue  ...         1      success   
41170       no   cellular   nov         wed  ...         4      failure   
41174       no   cellular   nov         thu  ...         6      success   

       emp.var.rate  cons.price.idx cons.conf.idx  euribor3m  nr.employed  \
2313            1.1          93.994         -36.4      4.856       5191.0   
4107            1.1          93.994         -36.4      4.858       5191.0   
4114            1.1          93.994         -36.4      4.858       5191.0   
4139            1.1          93.994         -36.4      4.858       5191.0   
4168            1.1          93.994         -36.4      4.858       5191.0   
...             ...             ...           ...        ...          ...   
41144          -1.1          94.767         -50.8      1.040       4963.6   
41153          -1.1          94.767         -50.8      1.039       4963.6   
41164          -1.1          94.767         -50.8      1.035       4963.6   
41170          -1.1          94.767         -50.8      1.030       4963.6   
41174          -1.1          94.767         -50.8      1.031       4963.6   

         y  Mahalanobis  Indices  
2313    no   146.930310     2313  
4107    no   389.027810     4107  
4114    no   181.137599     4114  
4139    no   144.110547     4139  
4168    no   213.025448     4168  
...    ...          ...      ...  
41144   no   129.243980    41144  
41153  yes   138.992647    41153  
41164  yes   103.602312    41164  
41170   no   127.991186    41170  
41174  yes   186.724262    41174  

[94 rows x 23 columns]

Conclusion: Al final nos queda 94 registros